services:
  - type: web
    name: neo-assistant
    env: python
    runtime: python3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: PORT
        value: "10000"